### ISSUE TITLE
Exception in Test Delivery from Gitea

### ISSUE THREAD

**Issue by flucrezia** [DavesCodeMusings/tea-runner#3]
Hi, I have just installed via docker compose the tool, but I'm getting the following when trying the APIs from Gitea, both /test and /rsync.

tea-runner  | ERROR: Exception on /rsync [POST]
tea-runner  | Traceback (most recent call last):
tea-runner  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
tea-runner  |     response = self.full_dispatch_request()
tea-runner  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1526, in full_dispatch_request
tea-runner  |     return self.finalize_request(rv)
tea-runner  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1545, in finalize_request
tea-runner  |     response = self.make_response(rv)
tea-runner  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1734, in make_response
tea-runner  |     raise TypeError(
tea-runner  | TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a bool.

I did not modify the code or the config file! Any hint?
Many thanks!

**Comment by DavesCodeMusings** [comment]
Check the `Content-type` header you're sending with the POST request. Make sure it's `Content-type: application/json`. I was able to recreate a similar error by not sending the header.

**Comment by DavesCodeMusings** [comment]
@flucrezia, I added a check for the `Content-type: application/javascript` header. If it's not supplied with the request, you should see an error in the log output.  I pushed a new container with the changes to Docker Hub. Give it a test when you have a chance.

**Comment by DavesCodeMusings** [comment]
Assuming the added check will fix the issue. Closing.
